import os
import time
import requests

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

def call_gemma(prompt: str, retries: int = 2) -> str:
    headers = {
        "Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:3000",
        "X-Title": "SAP Agentic Chatbot",
    }

    payload = {
        "model": "google/gemma-3-27b-it:free",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0,
    }

    for attempt in range(retries + 1):
        try:
            response = requests.post(
                OPENROUTER_URL,
                headers=headers,
                json=payload,
                timeout=60,
            )
            response.raise_for_status()
            data = response.json()

            if data.get("choices"):
                return data["choices"][0]["message"]["content"].strip()

            return "No response generated by the model."

        except requests.exceptions.HTTPError as e:
            # Retry only for 5xx errors
            if response.status_code >= 500 and attempt < retries:
                time.sleep(2 * (attempt + 1))
                continue
            return "⚠️ LLM service temporarily unavailable. Please try again."

        except requests.exceptions.RequestException:
            return "⚠️ Network error while contacting LLM service."

    return "⚠️ Unable to generate response at this time."
